export const designTokens = {
  color: {
    primary: "var(--ds-primary)",
    secondary: "var(--ds-secondary)",
    accent: "var(--ds-accent)",
    success: "var(--ds-success)",
    warning: "var(--ds-warning)",
    danger: "var(--ds-danger)",
    info: "var(--ds-info)",
    background: "var(--ds-background)",
    surface: "var(--ds-surface)",
    border: "var(--ds-border)",
    card: "var(--ds-card)",
    muted: "var(--ds-muted)",
    textPrimary: "var(--ds-text-primary)",
    textSecondary: "var(--ds-text-secondary)",
    textMuted: "var(--ds-text-muted)",
    glass: "var(--ds-glass)",
    overlay: "var(--ds-overlay)",
  },
  typography: {
    sans: "var(--font-inter)",
    mono: "var(--font-geist-mono)",
    displayXl: "clamp(4rem, 9vw, 8.5rem)",
    displayL: "clamp(3rem, 6vw, 6rem)",
    headingXl: "clamp(2.25rem, 4vw, 4rem)",
    headingL: "clamp(1.875rem, 3vw, 3rem)",
    headingM: "clamp(1.5rem, 2vw, 2rem)",
    headingS: "1.25rem",
    bodyLarge: "1.125rem",
    bodyMedium: "1rem",
    bodySmall: "0.875rem",
    caption: "0.75rem",
    overline: "0.6875rem",
    code: "0.875rem",
  },
  radius: {
    small: "var(--radius-small)",
    medium: "var(--radius-medium)",
    large: "var(--radius-large)",
    xl: "var(--radius-xl)",
    "2xl": "var(--radius-2xl)",
    full: "var(--radius-full)",
  },
  spacing: {
    4: "var(--space-4)",
    8: "var(--space-8)",
    12: "var(--space-12)",
    16: "var(--space-16)",
    20: "var(--space-20)",
    24: "var(--space-24)",
    32: "var(--space-32)",
    40: "var(--space-40)",
    48: "var(--space-48)",
    64: "var(--space-64)",
    80: "var(--space-80)",
    96: "var(--space-96)",
    128: "var(--space-128)",
    container: "var(--spacing-container)",
  },
  shadow: {
    soft: "var(--shadow-soft)",
    medium: "var(--shadow-medium)",
    strong: "var(--shadow-strong)",
    floating: "var(--shadow-floating)",
    glass: "var(--shadow-glass)",
    focus: "var(--shadow-focus)",
  },
  motion: {
    fast: "var(--duration-fast)",
    normal: "var(--duration-normal)",
    slow: "var(--duration-slow)",
    verySlow: "var(--duration-very-slow)",
    ease: "var(--ease)",
    easeIn: "var(--ease-in)",
    easeOut: "var(--ease-out)",
    easeInOut: "var(--ease-in-out)",
    bounce: "var(--bounce)",
    spring: "var(--spring)",
  },
  glass: {
    blur: "var(--glass-blur)",
    opacity: "var(--glass-opacity)",
    border: "var(--glass-border)",
    reflection: "var(--glass-reflection)",
    background: "var(--glass-background)",
    hover: "var(--glass-hover)",
    active: "var(--glass-active)",
  },
  blur: {
    glass: "var(--blur-glass)",
  },
  zIndex: {
    background: "var(--z-background)",
    scene: "var(--z-scene)",
    overlay: "var(--z-overlay)",
    popover: "var(--z-popover)",
    tooltip: "var(--z-tooltip)",
    modal: "var(--z-modal)",
    toast: "var(--z-toast)",
    critical: "var(--z-critical)",
  },
  container: {
    page: "var(--container-page)",
    reading: "var(--container-reading)",
  },
} as const;
